# Generated by Django 3.2 on 2021-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201229_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
