# Generated by Django 3.0.5 on 2021-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210527_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('Agar Nagar', 'Agar Nagar'), ('Kitchlu Nagar', 'Kitchlu Nagar'), ('Rajguru Nagar', 'Rajguru Nagar'), ('Field Ganj', 'Field Ganj'), ('Khud Mohalla', 'Khud Mohalla'), ('Miller Ganj', 'Miller Ganj'), ('Sarabha Nagar', 'Sarabha Nagar'), ('BRS Nagar', 'BRS Nagar'), ('Brown Road', 'Brown Road'), ('Pakhowal Road', 'Pakhowal Road'), ('Ghumar Mandi', 'Ghumar Mandi'), ('Model Town', 'Model Town'), ('New Shivaji Nagar', 'New Shivaji Nagar'), ('New Hargobind Nagar', 'New Hargobind Nagar'), ('Shivaji Nagar', 'Shivaji Nagar'), ('Hargobind Nagar', 'Hargobind Nagar'), ('Industrial Area', 'Industrial Area')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
