# Generated by Django 2.2.10 on 2021-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210528_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
